2024-03-03 04:01:04,981 Start MPyC runtime v0.9
2024-03-03 04:01:05,023 Start MPyC runtime v0.9
2024-03-03 04:01:05,100 All 2 parties connected.
Give your input here: 2024-03-03 04:01:05,100 All 2 parties connected.
Give your input here: here's your payload:  (b'TTWT5VHN4U55E625DJ7I95E8HRXKKCQ9xb5xf8xf1x11xe8Lxe4xf43Nxc5xfbxff!x9d&<@xfcx95x7fAx8fx9bcxd2Cr&xd0xdaxe5', b'2H5WAUJPJPKMV13HFKV6BADI02Y8RW2DD49JUBCYAGNBCWFNM97D559C5IUW1FKRTTWT5VHN4U55E625DJ7I95E8HRXKKCQ9xb5xf8xf1x11xe8Lxe4xf43Nxc5xfbxff!x9d&<@xfcx95x7fAx8fx9bcxd2Cr&xd0xdaxe5')
The given input is a secret key!
Give the other input here: here's your payload:  AZ6OOF3X83OGQOZ0T3193J
The given input is a message!
Give the other input here: here's the payload:  [<mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1aefd79a0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1aefd7880>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db6d0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db670>]
here's the inputs:  [[<mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db790>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db7f0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db820>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db850>], [<mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db7c0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db8b0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db8e0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7ff1a84db910>]]

Signing process begins now...
The length of the message and secret key is wrong! Please restart the function!
2024-03-03 04:01:06,094 Stop MPyC -- elapsed time: 0:00:00.993|bytes sent: 673
here's the payload:  [<mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a86b39a0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb1e70>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb1f30>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb36a0>]
here's the inputs:  [[<mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb3940>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb3f70>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb38e0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb3910>], [<mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb3e20>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1bb3ee0>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1968040>, <mpyc.sectypes.ArraySecFld1(GF(2)) object at 0x7f39a1968070>]]

Signing process begins now...
The length of the message and secret key is wrong! Please restart the function!
2024-03-03 04:01:06,094 Stop MPyC -- elapsed time: 0:00:00.994|bytes sent: 673
2024-03-03 04:01:06,100 Unhandled exception in event loop
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 431, in <lambda>
    task.add_done_callback(lambda t: _reconcile(decl, t))
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 355, in _reconcile
    givn = task.result()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 283, in _wrap_in_coro
    return await awaitable
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 271, in __await__
    val = self.coro.send(None)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/runtime.py", line 504, in output
    field = x[0].field
AttributeError: 'NoneType' object has no attribute 'field'
Traceback (enclosing MPyC coroutine call):
2024-03-03 04:01:06,107 Unhandled exception in event loop
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 431, in <lambda>
    task.add_done_callback(lambda t: _reconcile(decl, t))
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 355, in _reconcile
    givn = task.result()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 283, in _wrap_in_coro
    return await awaitable
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/asyncoro.py", line 271, in __await__
    val = self.coro.send(None)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/mpyc/runtime.py", line 504, in output
    field = x[0].field
AttributeError: 'NoneType' object has no attribute 'field'
Traceback (enclosing MPyC coroutine call):
